name: Build custom KeepassXC version

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: The KeepassXC version to build.

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Checkout KeepassXC
        run: |
          git init
          git remote add origin https://github.com/keepassxreboot/keepassxc.git
          git fetch origin
          git checkout ${{ inputs.version }}

      - name: Checkout patches
        uses: actions/checkout@v4
        with:
          path: _custom

      - name: Apply patches
        run: |
          git apply _custom/allow-screencapture.patch

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: |
          xcode-select --install
          brew install cmake asciidoctor qt@5 argon2 botan qrencode readline minizip

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DWITH_XC_ALL=ON -DCMAKE_PREFIX_PATH=$(brew --prefix qt@5)/lib/cmake -DKEEPASSXC_BUILD_TYPE=Release ..
          make

      - name: Create dmg
        run: cpack -G DragNDrop

      - name: Upload artifacts
        uses: actions/upload-artifacts@v4
        with:
          path: *.dmg
